//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.28 at 10:29:50 PM CEST 
//


package com.megatravel.mikroserviskorisnici.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipKorisnika.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipKorisnika">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="KORISNIK"/>
 *     &lt;enumeration value="ADMINISTRATOR"/>
 *     &lt;enumeration value="AGENT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TipKorisnika")
@XmlEnum
public enum TipKorisnika {

    KORISNIK,
    ADMINISTRATOR,
    AGENT;

    public String value() {
        return name();
    }

    public static TipKorisnika fromValue(String v) {
        return valueOf(v);
    }

}
