//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.28 at 10:29:43 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.megatravel.com/mikroservisocene/xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.megatravel.mikroservisocene.xml;
