//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.28 at 10:29:37 PM CEST 
//


package com.megatravel.mikroservissmestajnejedinice.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.megatravel.mikroservissmestajnejedinice.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.megatravel.mikroservissmestajnejedinice.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SveRezervacijeResponse }
     * 
     */
    public SveRezervacijeResponse createSveRezervacijeResponse() {
        return new SveRezervacijeResponse();
    }

    /**
     * Create an instance of {@link RezervacijaDTO }
     * 
     */
    public RezervacijaDTO createRezervacijaDTO() {
        return new RezervacijaDTO();
    }

    /**
     * Create an instance of {@link SviSmestajiResponse }
     * 
     */
    public SviSmestajiResponse createSviSmestajiResponse() {
        return new SviSmestajiResponse();
    }

    /**
     * Create an instance of {@link SmestajDTO }
     * 
     */
    public SmestajDTO createSmestajDTO() {
        return new SmestajDTO();
    }

    /**
     * Create an instance of {@link SviTipoviResponse }
     * 
     */
    public SviTipoviResponse createSviTipoviResponse() {
        return new SviTipoviResponse();
    }

    /**
     * Create an instance of {@link TipSmestajaDTO }
     * 
     */
    public TipSmestajaDTO createTipSmestajaDTO() {
        return new TipSmestajaDTO();
    }

    /**
     * Create an instance of {@link SveUslugeRequest }
     * 
     */
    public SveUslugeRequest createSveUslugeRequest() {
        return new SveUslugeRequest();
    }

    /**
     * Create an instance of {@link SveAdreseRequest }
     * 
     */
    public SveAdreseRequest createSveAdreseRequest() {
        return new SveAdreseRequest();
    }

    /**
     * Create an instance of {@link SviKomentariRequest }
     * 
     */
    public SviKomentariRequest createSviKomentariRequest() {
        return new SviKomentariRequest();
    }

    /**
     * Create an instance of {@link SveRezervacijeRequest }
     * 
     */
    public SveRezervacijeRequest createSveRezervacijeRequest() {
        return new SveRezervacijeRequest();
    }

    /**
     * Create an instance of {@link DodavanjeRezervacijeRequest }
     * 
     */
    public DodavanjeRezervacijeRequest createDodavanjeRezervacijeRequest() {
        return new DodavanjeRezervacijeRequest();
    }

    /**
     * Create an instance of {@link DodavanjeSmestajneJediniceRequest }
     * 
     */
    public DodavanjeSmestajneJediniceRequest createDodavanjeSmestajneJediniceRequest() {
        return new DodavanjeSmestajneJediniceRequest();
    }

    /**
     * Create an instance of {@link SviTipoviRequest }
     * 
     */
    public SviTipoviRequest createSviTipoviRequest() {
        return new SviTipoviRequest();
    }

    /**
     * Create an instance of {@link SviSmestajiRequest }
     * 
     */
    public SviSmestajiRequest createSviSmestajiRequest() {
        return new SviSmestajiRequest();
    }

    /**
     * Create an instance of {@link DodavanjeRezervacijeResponse }
     * 
     */
    public DodavanjeRezervacijeResponse createDodavanjeRezervacijeResponse() {
        return new DodavanjeRezervacijeResponse();
    }

    /**
     * Create an instance of {@link SveAdreseResponse }
     * 
     */
    public SveAdreseResponse createSveAdreseResponse() {
        return new SveAdreseResponse();
    }

    /**
     * Create an instance of {@link AdresaDTO }
     * 
     */
    public AdresaDTO createAdresaDTO() {
        return new AdresaDTO();
    }

    /**
     * Create an instance of {@link SveUslugeResponse }
     * 
     */
    public SveUslugeResponse createSveUslugeResponse() {
        return new SveUslugeResponse();
    }

    /**
     * Create an instance of {@link UslugaDTO }
     * 
     */
    public UslugaDTO createUslugaDTO() {
        return new UslugaDTO();
    }

    /**
     * Create an instance of {@link PotvrdaRezervacijeResponse }
     * 
     */
    public PotvrdaRezervacijeResponse createPotvrdaRezervacijeResponse() {
        return new PotvrdaRezervacijeResponse();
    }

    /**
     * Create an instance of {@link PotvrdaRezervacijeRequest }
     * 
     */
    public PotvrdaRezervacijeRequest createPotvrdaRezervacijeRequest() {
        return new PotvrdaRezervacijeRequest();
    }

    /**
     * Create an instance of {@link SviKomentariResponse }
     * 
     */
    public SviKomentariResponse createSviKomentariResponse() {
        return new SviKomentariResponse();
    }

    /**
     * Create an instance of {@link KomentarDTO }
     * 
     */
    public KomentarDTO createKomentarDTO() {
        return new KomentarDTO();
    }

    /**
     * Create an instance of {@link DodavanjeSmestajneJediniceResponse }
     * 
     */
    public DodavanjeSmestajneJediniceResponse createDodavanjeSmestajneJediniceResponse() {
        return new DodavanjeSmestajneJediniceResponse();
    }

}
