//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.28 at 10:29:58 PM CEST 
//


package com.megatravel.vebaplikacijaagent.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OcenaDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OcenaDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="vrednost" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="rezervacija" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OcenaDTO", namespace = "http://www.megatravel.com/mikroservisocene/xml", propOrder = {
    "id",
    "vrednost",
    "rezervacija"
})
public class OcenaDTO {

    protected long id;
    protected int vrednost;
    protected long rezervacija;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the vrednost property.
     * 
     */
    public int getVrednost() {
        return vrednost;
    }

    /**
     * Sets the value of the vrednost property.
     * 
     */
    public void setVrednost(int value) {
        this.vrednost = value;
    }

    /**
     * Gets the value of the rezervacija property.
     * 
     */
    public long getRezervacija() {
        return rezervacija;
    }

    /**
     * Sets the value of the rezervacija property.
     * 
     */
    public void setRezervacija(long value) {
        this.rezervacija = value;
    }

}
